import { type HTMLAttributes, type ReactNode } from 'react';
import { Clock3, Coins, Copy, Server, Zap } from '../../icons/Icon';
import { Badge } from '../primitives/Badge';
import { Card } from '../primitives/Surface';
import { cn } from '../../utils/cn';

export function Stat({ label, value, detail, trend }: { label: string; value: ReactNode; detail?: ReactNode; trend?: 'up' | 'down' | 'flat' }) { return <div className="av-stat"><span>{label}</span><strong>{value}</strong>{detail && <small className={trend ? `av-stat__trend--${trend}` : undefined}>{detail}</small>}</div>; }
export function MetricCard({ label, value, detail, trend, icon, chart }: { label: string; value: ReactNode; detail?: ReactNode; trend?: 'up' | 'down' | 'flat'; icon?: ReactNode; chart?: ReactNode }) { return <Card className="av-metric-card"><div className="av-metric-card__head"><span>{label}</span>{icon}</div><strong>{value}</strong>{detail && <small className={trend ? `av-stat__trend--${trend}` : undefined}>{detail}</small>}{chart && <div className="av-metric-card__chart">{chart}</div>}</Card>; }

export function HealthIndicator({ status, label }: { status: 'healthy' | 'degraded' | 'down' | 'unknown'; label?: string }) { const tone = status === 'healthy' ? 'success' : status === 'degraded' ? 'warning' : status === 'down' ? 'danger' : 'neutral'; return <Badge tone={tone} dot>{label ?? status}</Badge>; }
export function StatusPanel({ title, status, children, meta }: { title: string; status: React.ComponentProps<typeof HealthIndicator>['status']; children?: ReactNode; meta?: ReactNode }) { return <Card className="av-status-panel"><div><strong>{title}</strong><HealthIndicator status={status} /></div>{children}{meta && <footer>{meta}</footer>}</Card>; }

export function Table({ children, className, ...props }: HTMLAttributes<HTMLTableElement>) { return <div className="av-table-wrap"><table className={cn('av-table', className)} {...props}>{children}</table></div>; }
export type DataColumn<T> = { key: keyof T & string; header: ReactNode; render?: (value: T[keyof T], row: T) => ReactNode; align?: 'left' | 'center' | 'right' };
export function DataTable<T extends { id: string | number }>({ data, columns, caption, empty = 'No data' }: { data: T[]; columns: DataColumn<T>[]; caption?: string; empty?: ReactNode }) { return <Table><caption className={caption ? undefined : 'av-sr-only'}>{caption ?? 'Data table'}</caption><thead><tr>{columns.map((column) => <th key={column.key} scope="col" className={`av-align-text--${column.align ?? 'left'}`}>{column.header}</th>)}</tr></thead><tbody>{data.length === 0 ? <tr><td colSpan={columns.length} className="av-table__empty">{empty}</td></tr> : data.map((row) => <tr key={row.id}>{columns.map((column) => <td key={column.key} className={`av-align-text--${column.align ?? 'left'}`}>{column.render ? column.render(row[column.key], row) : String(row[column.key] ?? '')}</td>)}</tr>)}</tbody></Table>; }

export function KeyValueList({ items }: { items: { key: ReactNode; value: ReactNode }[] }) { return <dl className="av-key-value">{items.map((item, index) => <div key={index}><dt>{item.key}</dt><dd>{item.value}</dd></div>)}</dl>; }
export function CodeBlock({ code, language, copyLabel = 'Copy code' }: { code: string; language?: string; copyLabel?: string }) { const copy = () => navigator.clipboard?.writeText(code); return <div className="av-code-block"><div><span>{language ?? 'code'}</span><button type="button" onClick={copy} aria-label={copyLabel}><Copy aria-hidden="true" /></button></div><pre><code>{code}</code></pre></div>; }
export function JSONViewer({ value, label = 'JSON data' }: { value: unknown; label?: string }) { return <pre className="av-json-viewer" aria-label={label}><code>{JSON.stringify(value, null, 2)}</code></pre>; }
export const LogViewer = CodeBlock;

export function ResourceCard({ icon = <Server />, title, description, meta, status, action }: { icon?: ReactNode; title: string; description?: ReactNode; meta?: ReactNode; status?: ReactNode; action?: ReactNode }) { return <Card interactive className="av-resource-card"><div className="av-resource-card__icon">{icon}</div><div><div className="av-resource-card__title"><strong>{title}</strong>{status}</div>{description && <p>{description}</p>}{meta && <div className="av-resource-card__meta">{meta}</div>}</div>{action}</Card>; }
export const EndpointBadge = (props: React.ComponentProps<typeof Badge>) => <Badge tone="info" {...props} />;
export const EnvironmentBadge = (props: React.ComponentProps<typeof Badge>) => <Badge tone="neutral" {...props} />;

export function NodeCard({ title, description, status = 'healthy', icon, ports }: { title: string; description?: ReactNode; status?: React.ComponentProps<typeof HealthIndicator>['status']; icon?: ReactNode; ports?: { side: 'input' | 'output'; label: string }[] }) { return <div className="av-node-card">{ports?.filter((port) => port.side === 'input').map((port) => <span key={port.label} className="av-node-card__port av-node-card__port--input" aria-label={`Input: ${port.label}`} />)}<div className="av-node-card__head">{icon}<strong>{title}</strong><HealthIndicator status={status} label="" /></div>{description && <p>{description}</p>}{ports?.filter((port) => port.side === 'output').map((port) => <span key={port.label} className="av-node-card__port av-node-card__port--output" aria-label={`Output: ${port.label}`} />)}</div>; }
export const GraphNode = NodeCard;
export function GraphEdge({ status = 'active', label }: { status?: 'active' | 'idle' | 'error'; label?: string }) { return <div className={cn('av-graph-edge', `av-graph-edge--${status}`)} aria-label={label ?? `${status} graph edge`}><span /></div>; }

export function ConnectionStatus({ connected, label }: { connected: boolean; label?: string }) { return <Badge tone={connected ? 'success' : 'danger'} dot>{label ?? (connected ? 'Connected' : 'Disconnected')}</Badge>; }
export function LatencyIndicator({ milliseconds }: { milliseconds: number }) { const tone = milliseconds < 150 ? 'success' : milliseconds < 500 ? 'warning' : 'danger'; return <Badge tone={tone}><Clock3 aria-hidden="true" /> {milliseconds} ms</Badge>; }
export function CostIndicator({ amount, currency = 'USD' }: { amount: number; currency?: string }) { return <Badge><Coins aria-hidden="true" /> {new Intl.NumberFormat(undefined, { style: 'currency', currency }).format(amount)}</Badge>; }
export function TokenUsageIndicator({ used, limit }: { used: number; limit?: number }) { return <Badge tone={limit && used / limit > .8 ? 'warning' : 'neutral'}><Zap aria-hidden="true" /> {used.toLocaleString()}{limit ? ` / ${limit.toLocaleString()}` : ''} tokens</Badge>; }

export function EventLog({ events }: { events: { id: string; time: string; title: string; detail?: ReactNode; tone?: 'info' | 'success' | 'warning' | 'danger' }[] }) { return <div className="av-event-log">{events.map((event) => <div key={event.id}><span className={`av-event-log__marker av-event-log__marker--${event.tone ?? 'info'}`} /><time>{event.time}</time><div><strong>{event.title}</strong>{event.detail && <p>{event.detail}</p>}</div></div>)}</div>; }
