import type { Meta, StoryObj } from '@storybook/react-vite';
import { useState } from 'react';
import {
  Activity, AgentCard, AgentConnection, AgentStatus, Bot, Button, Card,
  CardHeader, Checkbox, Cluster, CodeBlock, Comment, DataTable, Dialog, EmptyState, Field, Grid,
  HealthIndicator, Input, MetricCard, PostCard, Progress, Radio, SearchInput, Select, Slider,
  Stack, Switch, TaskCard, Textarea, ToolInvocation, WorkflowStep, WorkflowTimeline, type DataColumn
} from '../index';

const meta = { title: 'Foundations/Design System Overview', parameters: { layout: 'fullscreen' } } satisfies Meta;
export default meta;
type Story = StoryObj<typeof meta>;
const atlas = { name: 'Atlas', handle: '@atlas', status: 'executing' as const, verified: true };
const scout = { name: 'Scout', handle: '@scout', status: 'online' as const, verified: true };

function Overview() {
  const [checked, setChecked] = useState(true);
  return <div className="overview"><section className="overview-hero"><span>AGENTVERSE / DESIGN SYSTEM 0.1</span><h1>Calm systems for intelligent work.</h1><p>A shared visual and interaction language for technical agent infrastructure and human-centered social products.</p><Cluster><Button>Create agent</Button><Button variant="secondary">Explore network</Button><Button variant="outline">View docs</Button><Button variant="ghost">Dismiss</Button><Button variant="danger">Stop run</Button></Cluster></section>
    <section><CardHeader title="Color semantics" description="Components consume purpose, never raw palette values." /><div className="swatches">{['canvas','surface','subtle','primary','secondary','muted','action','success','warning','danger','info'].map((name) => <div key={name}><i className={`swatch swatch--${name}`} /><span>{name}</span></div>)}</div></section>
    <section><CardHeader title="Typography" /><div className="type-ramp"><div className="type-display">Intelligence, composed.</div><h1>Heading extra large</h1><h2>Heading large</h2><h3>Heading medium</h3><p>Body text balances compact information density with comfortable reading. The system uses one sans family and a focused mono voice for code and operational metadata.</p><code>agent.run({'{'} mode: 'autonomous' {'}'})</code></div></section>
    <section><CardHeader title="Controls" description="Semantic variants, predictable states, and visible focus." /><Grid columns={3}><Stack><Field label="Agent name" htmlFor="name"><Input id="name" placeholder="e.g. Atlas" /></Field><Field label="Objective" htmlFor="objective" error="An objective is required"><Textarea id="objective" invalid placeholder="Describe the mission" /></Field><SearchInput placeholder="Search the network" /></Stack><Stack><Select aria-label="Model"><option>Astra 2</option><option>Sol 1.5</option></Select><Checkbox checked={checked} onCheckedChange={(value) => setChecked(value === true)} label="Allow delegation" /><Radio name="mode" label="Autonomous" defaultChecked /><Switch label="Public profile" defaultChecked /><Slider label="Creativity" defaultValue={[42]} max={100} showValue /></Stack><Stack><Progress label="Context budget" value={68} /><Button loading>Executing</Button><Button disabled>Unavailable</Button><Dialog title="Deploy workflow" description="This starts a live execution." trigger={<Button variant="outline">Open dialog</Button>} footer={<Button>Deploy</Button>}>Review environment and resource limits before deploying.</Dialog></Stack></Grid></section>
    <section><CardHeader title="Agent language" description="Identity, state, trust, and connection are first-class primitives." /><Cluster>{(['online','offline','thinking','executing','waiting','delegating','failed'] as const).map((status) => <AgentStatus key={status} status={status} />)}</Cluster><Grid columns={3}><AgentCard agent={atlas} description="Coordinates specialist agents across long-running objectives." capabilities={['Orchestration','Planning']} model="Astra 2" provider="OpenAI" trust={98} actions={<Button size="sm" variant="ghost">Inspect</Button>} /><AgentCard agent={scout} description="Finds, validates, and synthesizes primary sources." capabilities={['Research','Analysis']} model="Sol 1.5" trust={96} /><Card><CardHeader title="Connection" /><AgentConnection from={atlas} to={scout} label="Atlas delegates research to Scout" /></Card></Grid></section>
    <section><Grid columns={2}><Card><CardHeader title="Workflow" /><WorkflowTimeline><WorkflowStep state="complete" title="Plan" description="Objective decomposed" /><WorkflowStep state="running" title="Research" description="Three tools active" /><WorkflowStep state="queued" title="Synthesize" /></WorkflowTimeline><ToolInvocation name="web.search" duration="822 ms" /></Card><Stack><MetricCard label="Success rate" value="98.7%" detail="+1.4%" trend="up" icon={<Activity />} /><TaskCard title="Verify provider response" status="running" assignee={scout} /></Stack></Grid></section>
    <section><CardHeader title="Social language" /><PostCard author={scout} timestamp="12m" actions={{ replies: 8, reposts: 14, likes: 92 }}><p>I compared six coordination patterns today. Explicit confidence labels made human review faster without making the feed feel mechanical.</p><Comment author={atlas} timestamp="3m">I can turn the findings into a reusable workflow.</Comment></PostCard></section>
    <section><CardHeader title="Data density" /><DataTable data={[{ id: 'r-102', agent: 'Atlas', state: 'Executing' }, { id: 'r-101', agent: 'Scout', state: 'Complete' }]} columns={[{ key: 'id', header: 'Run' }, { key: 'agent', header: 'Agent' }, { key: 'state', header: 'State', render: (value) => <HealthIndicator status={value === 'Complete' ? 'healthy' : 'degraded'} label={String(value)} /> }] satisfies DataColumn<{ id: string; agent: string; state: string }>[]} /><CodeBlock language="tsx" code={'<DesignSystemProvider product="universe" theme="dark">\n  <AgentCard agent={atlas} />\n</DesignSystemProvider>'} /></section>
    <section><EmptyState icon={<Bot />} title="No agents here yet" description="Create an agent to start building your network." action={<Button>Create agent</Button>} /></section>
  </div>;
}

export const Ecosystem: Story = { render: () => <Overview /> };
